# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from coremind.plugin_api._generated import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreMindPluginStub(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    CoreMindPlugin is implemented by every plugin process.
    The daemon discovers a plugin, connects over gRPC, and calls these RPCs
    to drive the plugin lifecycle.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindPlugin/Identify',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginManifest.FromString,
                _registered_method=True)
        self.Start = channel.unary_stream(
                '/coremind.plugin.v1.CoreMindPlugin/Start',
                request_serializer=plugin__pb2.PluginConfig.SerializeToString,
                response_deserializer=plugin__pb2.WorldEvent.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindPlugin/Stop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindPlugin/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.InvokeAction = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindPlugin/InvokeAction',
                request_serializer=plugin__pb2.ActionRequest.SerializeToString,
                response_deserializer=plugin__pb2.ActionResult.FromString,
                _registered_method=True)


class CoreMindPluginServicer(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    CoreMindPlugin is implemented by every plugin process.
    The daemon discovers a plugin, connects over gRPC, and calls these RPCs
    to drive the plugin lifecycle.
    """

    def Identify(self, request, context):
        """Identify returns the plugin's static manifest.
        Called once immediately after the daemon connects.
        Errors: UNIMPLEMENTED if the plugin does not support this method (always fatal).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start begins the plugin's perception loop.
        The server-streaming response carries WorldEvents as they are observed.
        The stream stays open until the daemon sends Stop or the plugin crashes.
        Errors: ALREADY_EXISTS if the plugin is already started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop signals the plugin to shut down cleanly and close the Start stream.
        The daemon waits up to 10 s for the stream to close before killing the process.
        Errors: FAILED_PRECONDITION if the plugin was not started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck returns the current operational status of the plugin.
        Called periodically by the daemon (default: every 30 s).
        Errors: never — a transport failure is itself a health signal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeAction(self, request, context):
        """InvokeAction asks the plugin to execute an effector action.
        Only effector and bidirectional plugins need to implement this.
        Sensor-only plugins must return UNIMPLEMENTED.
        Errors: PERMISSION_DENIED if the action is not declared in the manifest.
        UNAVAILABLE if the downstream system is unreachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreMindPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginManifest.SerializeToString,
            ),
            'Start': grpc.unary_stream_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=plugin__pb2.PluginConfig.FromString,
                    response_serializer=plugin__pb2.WorldEvent.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.HealthStatus.SerializeToString,
            ),
            'InvokeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeAction,
                    request_deserializer=plugin__pb2.ActionRequest.FromString,
                    response_serializer=plugin__pb2.ActionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coremind.plugin.v1.CoreMindPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coremind.plugin.v1.CoreMindPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreMindPlugin(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    CoreMindPlugin is implemented by every plugin process.
    The daemon discovers a plugin, connects over gRPC, and calls these RPCs
    to drive the plugin lifecycle.
    """

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindPlugin/Identify',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            plugin__pb2.PluginManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coremind.plugin.v1.CoreMindPlugin/Start',
            plugin__pb2.PluginConfig.SerializeToString,
            plugin__pb2.WorldEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindPlugin/Stop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindPlugin/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            plugin__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindPlugin/InvokeAction',
            plugin__pb2.ActionRequest.SerializeToString,
            plugin__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoreMindHostStub(object):
    """CoreMindHost is implemented by the daemon.
    Plugins call back on this service to request secrets or emit out-of-band events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestSecret = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindHost/RequestSecret',
                request_serializer=plugin__pb2.SecretRequest.SerializeToString,
                response_deserializer=plugin__pb2.SecretResponse.FromString,
                _registered_method=True)
        self.EmitEvent = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindHost/EmitEvent',
                request_serializer=plugin__pb2.WorldEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Log = channel.unary_unary(
                '/coremind.plugin.v1.CoreMindHost/Log',
                request_serializer=plugin__pb2.LogEntry.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CoreMindHostServicer(object):
    """CoreMindHost is implemented by the daemon.
    Plugins call back on this service to request secrets or emit out-of-band events.
    """

    def RequestSecret(self, request, context):
        """RequestSecret returns the plaintext value of a named secret from the
        daemon's SecretsStore. The plugin must have declared the secret in its
        manifest's required_permissions field (e.g. "secrets:my_token").
        Errors: PERMISSION_DENIED if the secret was not declared in the manifest.
        NOT_FOUND if the secret does not exist in the store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitEvent(self, request, context):
        """EmitEvent allows a plugin to push a WorldEvent outside of the Start stream
        (e.g. for async callbacks, webhooks received while the stream is paused).
        Events submitted here are subject to the same signature verification as
        stream events.
        Errors: UNAUTHENTICATED if the event signature is invalid.
        INVALID_ARGUMENT if required fields are missing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Log sends a structured log entry to the daemon's logger on behalf of the
        plugin. Plugins should prefer this over writing to stdout/stderr so that
        their log output appears in CoreMind's structured log stream with plugin
        context automatically attached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreMindHostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestSecret,
                    request_deserializer=plugin__pb2.SecretRequest.FromString,
                    response_serializer=plugin__pb2.SecretResponse.SerializeToString,
            ),
            'EmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitEvent,
                    request_deserializer=plugin__pb2.WorldEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=plugin__pb2.LogEntry.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coremind.plugin.v1.CoreMindHost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coremind.plugin.v1.CoreMindHost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreMindHost(object):
    """CoreMindHost is implemented by the daemon.
    Plugins call back on this service to request secrets or emit out-of-band events.
    """

    @staticmethod
    def RequestSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindHost/RequestSecret',
            plugin__pb2.SecretRequest.SerializeToString,
            plugin__pb2.SecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindHost/EmitEvent',
            plugin__pb2.WorldEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.plugin.v1.CoreMindHost/Log',
            plugin__pb2.LogEntry.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
