# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coremind_plugin_openclaw._generated import adapter_pb2 as adapter__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from coremind.plugin_api._generated import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreMindHalfStub(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    CoreMindHalf is implemented by the CoreMind-side plugin.
    The OpenClaw extension connects to it as a gRPC client and forwards
    adapter-local events (already translated to WorldEvent form) and
    health probes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestEvent = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.CoreMindHalf/IngestEvent',
                request_serializer=plugin__pb2.WorldEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.CoreMindHalf/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adapter__pb2.Health.FromString,
                _registered_method=True)


class CoreMindHalfServicer(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    CoreMindHalf is implemented by the CoreMind-side plugin.
    The OpenClaw extension connects to it as a gRPC client and forwards
    adapter-local events (already translated to WorldEvent form) and
    health probes.
    """

    def IngestEvent(self, request, context):
        """IngestEvent accepts a signed WorldEvent from the OpenClaw side and
        publishes it onto the CoreMind daemon's event stream.
        Signature verification follows the same rules as CoreMindHost.EmitEvent.
        Errors: UNAUTHENTICATED on bad signature.
        INVALID_ARGUMENT on malformed event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck returns the CoreMind side's operational status.
        Called periodically by the OpenClaw side for liveness detection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreMindHalfServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=plugin__pb2.WorldEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adapter__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coremind.openclaw_adapter.v1.CoreMindHalf', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coremind.openclaw_adapter.v1.CoreMindHalf', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreMindHalf(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    CoreMindHalf is implemented by the CoreMind-side plugin.
    The OpenClaw extension connects to it as a gRPC client and forwards
    adapter-local events (already translated to WorldEvent form) and
    health probes.
    """

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.CoreMindHalf/IngestEvent',
            plugin__pb2.WorldEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.CoreMindHalf/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adapter__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OpenClawHalfStub(object):
    """OpenClawHalf is implemented by the OpenClaw-side extension.
    The CoreMind plugin connects to it as a gRPC client to dispatch
    effector actions against OpenClaw's channels, skills and cron scheduler.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notify = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/Notify',
                request_serializer=adapter__pb2.NotifyRequest.SerializeToString,
                response_deserializer=adapter__pb2.NotifyResult.FromString,
                _registered_method=True)
        self.RequestApproval = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/RequestApproval',
                request_serializer=adapter__pb2.ApprovalRequest.SerializeToString,
                response_deserializer=adapter__pb2.ApprovalResult.FromString,
                _registered_method=True)
        self.InvokeSkill = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/InvokeSkill',
                request_serializer=adapter__pb2.SkillInvocation.SerializeToString,
                response_deserializer=adapter__pb2.SkillResult.FromString,
                _registered_method=True)
        self.ScheduleCron = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/ScheduleCron',
                request_serializer=adapter__pb2.CronScheduleRequest.SerializeToString,
                response_deserializer=adapter__pb2.CronScheduleResult.FromString,
                _registered_method=True)
        self.CancelCron = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/CancelCron',
                request_serializer=adapter__pb2.CronCancelRequest.SerializeToString,
                response_deserializer=adapter__pb2.CronCancelResult.FromString,
                _registered_method=True)
        self.Mem0Query = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/Mem0Query',
                request_serializer=adapter__pb2.Mem0QueryRequest.SerializeToString,
                response_deserializer=adapter__pb2.Mem0QueryResult.FromString,
                _registered_method=True)
        self.Mem0Store = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/Mem0Store',
                request_serializer=adapter__pb2.Mem0StoreRequest.SerializeToString,
                response_deserializer=adapter__pb2.Mem0StoreResult.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/ListChannels',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adapter__pb2.ChannelList.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/ListSkills',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adapter__pb2.SkillList.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/coremind.openclaw_adapter.v1.OpenClawHalf/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adapter__pb2.Health.FromString,
                _registered_method=True)


class OpenClawHalfServicer(object):
    """OpenClawHalf is implemented by the OpenClaw-side extension.
    The CoreMind plugin connects to it as a gRPC client to dispatch
    effector actions against OpenClaw's channels, skills and cron scheduler.
    """

    def Notify(self, request, context):
        """Notify delivers a text message on a named OpenClaw channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestApproval(self, request, context):
        """RequestApproval opens an approval dialog through OpenClaw's approval UI
        and returns the outcome (approved / denied / timed out).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeSkill(self, request, context):
        """InvokeSkill triggers a registered OpenClaw skill by name with parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleCron(self, request, context):
        """ScheduleCron registers a new cron entry in OpenClaw's scheduler.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelCron(self, request, context):
        """CancelCron removes a previously scheduled cron entry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mem0Query(self, request, context):
        """Mem0Query reads from OpenClaw's mem0 semantic store (optional backend).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mem0Store(self, request, context):
        """Mem0Store writes to OpenClaw's mem0 semantic store (optional backend).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """ListChannels returns the set of channel identifiers the extension can
        reach with its current configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """ListSkills returns the set of skills registered in the OpenClaw gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck returns the OpenClaw side's operational status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenClawHalfServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=adapter__pb2.NotifyRequest.FromString,
                    response_serializer=adapter__pb2.NotifyResult.SerializeToString,
            ),
            'RequestApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestApproval,
                    request_deserializer=adapter__pb2.ApprovalRequest.FromString,
                    response_serializer=adapter__pb2.ApprovalResult.SerializeToString,
            ),
            'InvokeSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeSkill,
                    request_deserializer=adapter__pb2.SkillInvocation.FromString,
                    response_serializer=adapter__pb2.SkillResult.SerializeToString,
            ),
            'ScheduleCron': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleCron,
                    request_deserializer=adapter__pb2.CronScheduleRequest.FromString,
                    response_serializer=adapter__pb2.CronScheduleResult.SerializeToString,
            ),
            'CancelCron': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelCron,
                    request_deserializer=adapter__pb2.CronCancelRequest.FromString,
                    response_serializer=adapter__pb2.CronCancelResult.SerializeToString,
            ),
            'Mem0Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Mem0Query,
                    request_deserializer=adapter__pb2.Mem0QueryRequest.FromString,
                    response_serializer=adapter__pb2.Mem0QueryResult.SerializeToString,
            ),
            'Mem0Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Mem0Store,
                    request_deserializer=adapter__pb2.Mem0StoreRequest.FromString,
                    response_serializer=adapter__pb2.Mem0StoreResult.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adapter__pb2.ChannelList.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adapter__pb2.SkillList.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adapter__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coremind.openclaw_adapter.v1.OpenClawHalf', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coremind.openclaw_adapter.v1.OpenClawHalf', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenClawHalf(object):
    """OpenClawHalf is implemented by the OpenClaw-side extension.
    The CoreMind plugin connects to it as a gRPC client to dispatch
    effector actions against OpenClaw's channels, skills and cron scheduler.
    """

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/Notify',
            adapter__pb2.NotifyRequest.SerializeToString,
            adapter__pb2.NotifyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/RequestApproval',
            adapter__pb2.ApprovalRequest.SerializeToString,
            adapter__pb2.ApprovalResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/InvokeSkill',
            adapter__pb2.SkillInvocation.SerializeToString,
            adapter__pb2.SkillResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/ScheduleCron',
            adapter__pb2.CronScheduleRequest.SerializeToString,
            adapter__pb2.CronScheduleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/CancelCron',
            adapter__pb2.CronCancelRequest.SerializeToString,
            adapter__pb2.CronCancelResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mem0Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/Mem0Query',
            adapter__pb2.Mem0QueryRequest.SerializeToString,
            adapter__pb2.Mem0QueryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mem0Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/Mem0Store',
            adapter__pb2.Mem0StoreRequest.SerializeToString,
            adapter__pb2.Mem0StoreResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/ListChannels',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adapter__pb2.ChannelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/ListSkills',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adapter__pb2.SkillList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coremind.openclaw_adapter.v1.OpenClawHalf/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adapter__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
