"""Cryptographic identity, signing, and verification for CoreMind.

Uses ed25519 keys (via the ``cryptography`` library) for all signing
operations, and RFC 8785 JCS (via ``jcs``) for canonical serialisation
so that signatures are reproducible across runtimes and platforms.

Key layout on disk:
  ~/.coremind/keys/daemon.ed25519       — daemon private key (chmod 600)
  ~/.coremind/keys/daemon.ed25519.pub   — daemon public key
  ~/.coremind/keys/plugins/<id>.ed25519     — plugin private key (chmod 600)
  ~/.coremind/keys/plugins/<id>.ed25519.pub — plugin public key
"""

from __future__ import annotations

import contextlib
import os
import re
import stat
import tempfile
from pathlib import Path

import jcs  # type: ignore[import-untyped]  # jcs has no py.typed marker
import structlog
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
    load_pem_private_key,
    load_pem_public_key,
)

from coremind.errors import KeyManagementError

log = structlog.get_logger(__name__)

_KEYS_DIR_MODE = 0o700
_KEY_FILE_MODE = 0o600
_PLUGIN_ID_RE: re.Pattern[str] = re.compile(r"^[a-zA-Z0-9_-]+$")


# ---------------------------------------------------------------------------
# Public signing/verification API
# ---------------------------------------------------------------------------


def sign(payload_bytes: bytes, private_key: Ed25519PrivateKey) -> bytes:
    """Sign *payload_bytes* with *private_key* and return the raw 64-byte signature.

    Args:
        payload_bytes: The raw bytes to sign. Callers should serialise
            structured data with :func:`canonical_json` first.
        private_key: An ed25519 private key loaded or generated by this module.

    Returns:
        A 64-byte ed25519 signature.
    """
    result: bytes = private_key.sign(payload_bytes)
    return result


def verify(
    payload_bytes: bytes,
    signature: bytes,
    public_key: Ed25519PublicKey,
) -> bool:
    """Verify *signature* over *payload_bytes* using *public_key*.

    Args:
        payload_bytes: The exact bytes that were signed.
        signature: The 64-byte signature to verify.
        public_key: The ed25519 public key of the signer.

    Returns:
        ``True`` if the signature is valid, ``False`` otherwise.
    """
    try:
        public_key.verify(signature, payload_bytes)
    except InvalidSignature:
        return False
    return True


def canonical_json(obj: dict[str, object]) -> bytes:
    """Serialise *obj* to RFC 8785 (JCS) canonical JSON bytes.

    The output is deterministic regardless of key insertion order or
    platform, making it safe to use as signed payload.

    Args:
        obj: A JSON-serialisable dict. Nested objects are supported.

    Returns:
        UTF-8 encoded canonical JSON bytes.
    """
    return jcs.canonicalize(obj)  # type: ignore[no-any-return]


# ---------------------------------------------------------------------------
# Key management
# ---------------------------------------------------------------------------


def _keys_root() -> Path:
    """Return the base directory for key storage, creating it if absent."""
    root = Path.home() / ".coremind" / "keys"
    root.mkdir(parents=True, exist_ok=True)
    root.chmod(_KEYS_DIR_MODE)
    return root


def _atomic_write(path: Path, data: bytes, mode: int = 0o644) -> None:
    """Write *data* to *path* atomically via a temp file and rename.

    Creates a temporary file in the same directory, writes *data* to it,
    sets permissions to *mode*, then renames into place.  The rename is
    atomic on POSIX filesystems, so readers never see a partial write.

    Args:
        path: Destination path.
        data: Raw bytes to write.
        mode: File permission bits (default 0o644).
    """
    fd, tmp = tempfile.mkstemp(dir=path.parent)
    tmp_path = Path(tmp)
    try:
        os.write(fd, data)
        os.fchmod(fd, mode)
        os.close(fd)
        tmp_path.rename(path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.close(fd)
        tmp_path.unlink(missing_ok=True)
        raise


def _write_keypair(private_path: Path, public_path: Path, key: Ed25519PrivateKey) -> None:
    """Persist *key* (private + public) to *private_path* and *public_path*.

    Both files are written atomically via a temp file to avoid partial writes.
    The private key file is chmod 600.

    Args:
        private_path: Destination for the PEM-encoded private key.
        public_path: Destination for the PEM-encoded public key.
        key: The ed25519 private key to serialise.
    """
    private_pem = key.private_bytes(
        encoding=Encoding.PEM,
        format=PrivateFormat.PKCS8,
        encryption_algorithm=NoEncryption(),
    )
    public_pem = key.public_key().public_bytes(
        encoding=Encoding.PEM,
        format=PublicFormat.SubjectPublicKeyInfo,
    )

    private_path.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(private_path, private_pem, _KEY_FILE_MODE)

    public_path.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(public_path, public_pem)


def _load_private_key(path: Path) -> Ed25519PrivateKey:
    """Load a PEM-encoded ed25519 private key from *path*.

    Args:
        path: Filesystem path to the PEM key file.

    Returns:
        The loaded :class:`Ed25519PrivateKey`.

    Raises:
        KeyManagementError: If the file cannot be read or parsed.
    """
    try:
        pem_bytes = path.read_bytes()
        key = load_pem_private_key(pem_bytes, password=None)
    except (OSError, ValueError, TypeError) as exc:
        raise KeyManagementError(f"Failed to load private key from {path}: {exc}") from exc
    if not isinstance(key, Ed25519PrivateKey):
        raise KeyManagementError(f"Key at {path} is not an ed25519 private key")
    return key


def load_public_key(path: Path) -> Ed25519PublicKey:
    """Load a PEM-encoded ed25519 public key from *path*.

    Args:
        path: Filesystem path to the PEM public key file.

    Returns:
        The loaded :class:`Ed25519PublicKey`.

    Raises:
        KeyManagementError: If the file cannot be read or parsed.
    """
    try:
        pem_bytes = path.read_bytes()
        key = load_pem_public_key(pem_bytes)
    except (OSError, ValueError, TypeError) as exc:
        raise KeyManagementError(f"Failed to load public key from {path}: {exc}") from exc
    if not isinstance(key, Ed25519PublicKey):
        raise KeyManagementError(f"Key at {path} is not an ed25519 public key")
    return key


def ensure_daemon_keypair() -> Ed25519PrivateKey:
    """Return the daemon's ed25519 private key, generating it on first call.

    The private key is stored at ``~/.coremind/keys/daemon.ed25519`` with
    mode 0o600.  The corresponding public key is written alongside it at
    ``~/.coremind/keys/daemon.ed25519.pub``.

    Returns:
        The daemon's :class:`Ed25519PrivateKey`.

    Raises:
        KeyManagementError: If the key cannot be read or written.
    """
    root = _keys_root()
    private_path = root / "daemon.ed25519"
    public_path = root / "daemon.ed25519.pub"

    if private_path.exists():
        _assert_mode(private_path)
        return _load_private_key(private_path)

    log.info("generating_daemon_keypair", path=str(private_path))
    key = Ed25519PrivateKey.generate()
    _write_keypair(private_path, public_path, key)
    return key


def ensure_plugin_keypair(plugin_id: str) -> Ed25519PrivateKey:
    """Return (or generate) an ed25519 keypair for *plugin_id*.

    Keys are stored at:
      ``~/.coremind/keys/plugins/<plugin_id>.ed25519``
      ``~/.coremind/keys/plugins/<plugin_id>.ed25519.pub``

    Args:
        plugin_id: Unique, URL-safe identifier for the plugin.

    Returns:
        The plugin's :class:`Ed25519PrivateKey`.

    Raises:
        KeyManagementError: If the key cannot be read or written.
        ValueError: If *plugin_id* is empty.
    """
    if not plugin_id:
        raise ValueError("plugin_id must not be empty")
    if not _PLUGIN_ID_RE.match(plugin_id):
        raise ValueError("plugin_id must contain only [a-zA-Z0-9_-]")

    plugins_dir = _keys_root() / "plugins"
    private_path = plugins_dir / f"{plugin_id}.ed25519"
    public_path = plugins_dir / f"{plugin_id}.ed25519.pub"

    if private_path.exists():
        _assert_mode(private_path)
        return _load_private_key(private_path)

    log.info("generating_plugin_keypair", plugin_id=plugin_id, path=str(private_path))
    key = Ed25519PrivateKey.generate()
    _write_keypair(private_path, public_path, key)
    return key


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _assert_mode(path: Path) -> None:
    """Raise :exc:`KeyManagementError` if *path* has permissions wider than 0o600.

    Args:
        path: The file to check.

    Raises:
        KeyManagementError: If the file permissions are wider than 0o600.
    """
    current = stat.S_IMODE(path.stat().st_mode)
    if current & ~_KEY_FILE_MODE:
        expected = oct(_KEY_FILE_MODE)
        raise KeyManagementError(
            f"key file permissions too open: {path} has {oct(current)}, expected {expected}"
        )
