"""Slider graduation — proposes autonomy slider increases based on approval history.

When L7/L8 detects a domain with consistently high approval rates (the user
approves the system's actions in that domain repeatedly), the graduation
evaluator proposes a slider increase.  Proposals require explicit user
approval before taking effect.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

from pydantic import BaseModel, ConfigDict, Field

from coremind.action.autonomy import AutonomyConfig, GraduationConfig, classify_domain


class SliderGraduationProposal(BaseModel):
    """A proposal to increase a domain's autonomy slider.

    Generated by :class:`GraduationEvaluator` when approval history meets
    the configured thresholds.
    """

    model_config = ConfigDict(frozen=True)

    proposal_id: str = Field(min_length=1)
    domain: str = Field(min_length=1)
    current_slider: float = Field(ge=0.0, le=1.0)
    proposed_slider: float = Field(ge=0.0, le=1.0)
    approval_rate: float = Field(ge=0.0, le=1.0)
    total_actions: int = Field(ge=0)
    approved_actions: int = Field(ge=0)
    observation_window_days: int = Field(ge=1)
    proposed_at: datetime


class ActionOutcome(BaseModel):
    """Minimal action record needed for graduation evaluation.

    Attributes:
        action_class: The action's class (e.g. "light.turn_on").
        approved: Whether the action was approved/executed successfully.
        timestamp: When the action was executed or decided.
    """

    model_config = ConfigDict(frozen=True)

    action_class: str
    approved: bool
    timestamp: datetime


class GraduationEvaluator:
    """Evaluate whether a domain qualifies for a slider promotion.

    Args:
        config: The graduation configuration thresholds.
        last_promotions: Mapping of domain → timestamp of last promotion,
            used for cooldown enforcement.
    """

    def __init__(
        self,
        config: GraduationConfig,
        *,
        last_promotions: dict[str, datetime] | None = None,
    ) -> None:
        self._config = config
        self._last_promotions = last_promotions or {}

    def evaluate(
        self,
        domain: str,
        current_slider: float,
        action_history: list[ActionOutcome],
    ) -> SliderGraduationProposal | None:
        """Return a promotion proposal if the domain qualifies, else None.

        Args:
            domain: The domain to evaluate (e.g. "lights").
            current_slider: The current slider value for this domain.
            action_history: Recent action outcomes to analyze.

        Returns:
            A :class:`SliderGraduationProposal` if thresholds are met,
            or ``None`` if the domain does not qualify.
        """
        if not self._config.enabled:
            return None

        if current_slider >= 1.0:
            return None  # Already at maximum.

        # Enforce cooldown.
        last = self._last_promotions.get(domain)
        now = datetime.now(UTC)
        if last is not None:
            cooldown = timedelta(days=self._config.promotion_cooldown_days)
            if now - last < cooldown:
                return None

        # Filter actions for this domain within the observation window.
        cutoff = now - timedelta(days=self._config.min_observation_days)
        relevant = [
            a
            for a in action_history
            if classify_domain(a.action_class) == domain and a.timestamp >= cutoff
        ]

        if len(relevant) < self._config.min_approvals_before_promotion:
            return None

        approved_count = sum(1 for a in relevant if a.approved)
        approval_rate = approved_count / len(relevant)

        if approval_rate < self._config.min_approval_rate_for_promotion:
            return None

        # Calculate new slider (capped by max_promotion_per_proposal).
        increase = min(self._config.max_promotion_per_proposal, 1.0 - current_slider)
        new_slider = round(current_slider + increase, 2)

        return SliderGraduationProposal(
            proposal_id=f"grad_{domain}_{now.strftime('%Y%m%d%H%M%S')}",
            domain=domain,
            current_slider=current_slider,
            proposed_slider=new_slider,
            approval_rate=round(approval_rate, 3),
            total_actions=len(relevant),
            approved_actions=approved_count,
            observation_window_days=self._config.min_observation_days,
            proposed_at=now,
        )

    def evaluate_all(
        self,
        autonomy_config: AutonomyConfig,
        action_history: list[ActionOutcome],
    ) -> list[SliderGraduationProposal]:
        """Evaluate all configured domains for graduation.

        Args:
            autonomy_config: The full autonomy configuration.
            action_history: Recent action outcomes across all domains.

        Returns:
            A list of proposals for domains that qualify.
        """
        proposals: list[SliderGraduationProposal] = []
        for domain, slider in autonomy_config.domains.items():
            proposal = self.evaluate(domain, slider, action_history)
            if proposal is not None:
                proposals.append(proposal)
        return proposals
